version: '3.8'
services:
  mariadb:
    build:
      context: mariadb
    env_file:
    - mariadb/.env
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - frontend

  nginx:
    build:
      context: nginx
    env_file:
    - nginx/.env
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - 443:443
    networks:
      - frontend

  php:
    build:
      context: wordpress
    env_file:
      - wordpress/.env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - frontend
    extra_hosts:
      - "khorike.42.jp:127.0.0.1"

networks:
  frontend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/khorike/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/khorike/data/wordpress